version: "3.8"

name: nuxt-nest_dev

services:
  client:
    container_name: "nuxt-nest_client_dev"
    build:
      context: ./client
      dockerfile: Dockerfile_dev
    expose:
      - 3000
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./client:/app
  server:
    container_name: "nuxt-nest_server_dev"
    restart: always
    build:
      context: server
      dockerfile: Dockerfile_dev
    # выставляем права чтобы можно 
    # созданные файлы через docker контейнер
    # могли быть изменнены на хосте
    user: 1000:1000
    expose:
      - 5000
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./server:/app
  nginx:
    image: nginx
    restart: "no"
    container_name: "nuxt-nest_nginx_dev"
    ports:
      - 7000:80
    depends_on:
      - server
      - client
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./nginx/dev:/etc/nginx/nuxt-nest
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
