version: "3.8"

name: nuxt-nest_prod

services:
  client:
    container_name: "nuxt-nest_client_prod"
    build: client
    command: npm run start
    expose:
      - 3000
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /app/node_modules
  server:
    container_name: "nuxt-nest_server_prod"
    restart: always
    build: server
    command: npm run start:prod
    expose:
      - 5000
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /app/node_modules
  nginx:
    image: nginx
    restart: "no"
    container_name: "nuxt-nest_nginx_prod"
    ports:
      - 80:80
    depends_on:
      - server
      - client
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./nginx/prod:/etc/nginx/nuxt-nest
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
