version: "3.7"

services:
  nuxt-nest_client:
    container_name: "nuxt-nest_client"
    build:
      context: ./client
      dockerfile: Dockerfile_dev
    command: npm run dev
    expose:
      - 3000
    ports:
      # nuxt hmr port
      - 24678:24678
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./client:/app
      - ./client/dist:/app/dist
      - /app/node_modules
  nuxt-nest_server:
    container_name: "nuxt-nest_server"
    restart: always
    build:
      context: server
      dockerfile: Dockerfile_dev
    command: npm run start:dev
    expose:
      - 5000
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./server:/app
      - /app/node_modules
  nuxt-nest_nginx:
    image: nginx
    restart: "no"
    container_name: "nuxt-nest_nginx"
    ports:
      - 7000:80
    depends_on:
      - nuxt-nest_server
      - nuxt-nest_client
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./nginx/dev:/etc/nginx/nuxt-nest
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf

